version: '3'

services:
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn --bind 0:8000 config.wsgi:application
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pybo_db_user
      - POSTGRES_PASSWORD=pybo_db_password
      - POSTGRES_DB=pybo_dev
volumes:
  postgres_data:
